### Register a new user

POST http://localhost:3010/register
Content-Type: application/json

{
  "name": "yurina"
}

### Send a transaction

POST http://localhost:3010/send
Content-Type: application/json

{
  "from_address": "0xc92e12f3a0df04e081cd2c6410c8e554b695b0dd",
  "to_address": "0xc1d158bfd476156099bfc1b701fb021d543fdb82",
  "amount": 5,
  "private_key": "d1fc08820e7cb02c289acbc99d92a11a79a649b1a941a590b1de6ee5a3f54712"
}

### Send a transaction 2

POST http://localhost:3010/send
Content-Type: application/json

{
  "from_address": "FAKE-80a7e7b6d48b7f314ac5c57a5b2a0904",
  "to_address": "FAKE-26ae0ededb163e79a89eb0e605cc39f7",
  "amount": 50,
  "private_key": "08f2f7fc1f144cda46bfa0560ec0876aedf6a2c44b8e1c6dde4ae6a77471aa46"
}


### Get transaction by ID
GET http://localhost:3010/transaction/122

### get balance by address
GET http://localhost:3010/balance/0xc1d158bfd476156099bfc1b701fb021d543fdb82

### generate blocks
POST http://localhost:3010/generate-block

### get blocks
GET http://localhost:3010/blocks?limit=10&offset=0

### get detail blocks
GET http://localhost:3010/blocks/detail/2

### get block by ID
GET http://localhost:3010/blocks/2

### check blockchain integrity
GET http://localhost:3010/blocks/integrity

### get reward info
GET http://localhost:3010/reward/info

### get block reward
GET http://localhost:3010/reward/block/2

### get schedule
GET http://localhost:3010/reward/schedule/10

### get wallet balance
GET http://localhost:3010/wallet/0xc92e12f3a0df04e081cd2c6410c8e554b695b0dd?page=1&limit=5&type=received&status=confirmed&order=desc

## challenge request
POST http://localhost:3010/challenge/0xce4b0c6afb4a5c27922557f5cb3d3e1b6ef496b0

## challenge verify request
POST http://localhost:3010/challenge/verify
Content-Type: application/json

{
  "address": "0xce4b0c6afb4a5c27922557f5cb3d3e1b6ef496b0",
  "signature": "0x2c6404e5f3cf3f2a4d5f7c6b4c8e2f3a4b5c6d7e8f9a0b1c2d3e4f506172839405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20"
}